/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  OrderApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { KlarnaCheckoutCustom } from "./client-custom";

export class KlarnaCheckout extends KlarnaCheckoutCustom {
  readonly order: OrderApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.order = new OrderApi(configuration);
  }

}
