/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * Title.<p>Valid values for UK:</p><ul><li><em>Mr</em></li><li><em>Ms</em></li><li><em>Mrs</em></li><li><em>Miss</em></li></ul><p>Valid values for DACH:</p><ul><li><em>Herr</em></li><li><em>Frau</em></li></ul><p>Valid values for NL:</p><ul><li><em>Dhr.</em></li><li><em>Mevr.</em></li></ul>
     * @type {string}
     * @memberof Address
     */
    'title'?: string;
    /**
     * Given name.
     * @type {string}
     * @memberof Address
     */
    'given_name'?: string;
    /**
     * Family name.
     * @type {string}
     * @memberof Address
     */
    'family_name'?: string;
    /**
     * E-mail address.
     * @type {string}
     * @memberof Address
     */
    'email'?: string;
    /**
     * Street address, first line. (Street name and number)
     * @type {string}
     * @memberof Address
     */
    'street_address'?: string;
    /**
     * Street address, second line. (Apartment number, suite, etc.)
     * @type {string}
     * @memberof Address
     */
    'street_address2'?: string;
    /**
     * Street name. Only applicable in DE/AT/NL. Do not combine with street_address. See <b>streetNumber</b>.
     * @type {string}
     * @memberof Address
     */
    'street_name'?: string;
    /**
     * Street number. Only applicable in DE/AT/NL. Do not combine with street_address. See <b>streetName</b>.
     * @type {string}
     * @memberof Address
     */
    'street_number'?: string;
    /**
     * House extension. Only applicable in NL
     * @type {string}
     * @memberof Address
     */
    'house_extension'?: string;
    /**
     * Postal/post code.
     * @type {string}
     * @memberof Address
     */
    'postal_code'?: string;
    /**
     * City.
     * @type {string}
     * @memberof Address
     */
    'city'?: string;
    /**
     * State or Region.
     * @type {string}
     * @memberof Address
     */
    'region'?: string;
    /**
     * Phone number.
     * @type {string}
     * @memberof Address
     */
    'phone'?: string;
    /**
     * ISO 3166 alpha-2. Country.
     * @type {string}
     * @memberof Address
     */
    'country'?: string;
    /**
     * Care of.
     * @type {string}
     * @memberof Address
     */
    'care_of'?: string;
}

