/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Checkbox
 */
export interface Checkbox {
    /**
     * Text that will be displayed to the consumer aside the checkbox. Links and formatting can be added using Markdown. (max 1000 characters)
     * @type {string}
     * @memberof Checkbox
     */
    'text': string;
    /**
     * Default state of the additional checkbox. It will use this value when loaded for the first time.
     * @type {boolean}
     * @memberof Checkbox
     */
    'checked': boolean;
    /**
     * Whether it is required for the consumer to check the additional checkbox box or not in order to complete the purchase.
     * @type {boolean}
     * @memberof Checkbox
     */
    'required': boolean;
}

