/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * The default supported value is \'person\'. If B2B is enabled for the merchant, the value may be \"organization\".
     * @type {string}
     * @memberof Customer
     */
    'type'?: string;
    /**
     * Customer’s gender - ‘male’ or ‘female’.
     * @type {string}
     * @memberof Customer
     */
    'gender'?: string;
    /**
     * Customer’s date of birth. The format is ‘yyyy-mm-dd’. ISO 8601 date.
     * @type {string}
     * @memberof Customer
     */
    'date_of_birth'?: string;
    /**
     * \"The organization\'s official registration id (organization number).  Note: Applicable only for B2B orders.\"
     * @type {string}
     * @memberof Customer
     */
    'organization_registration_id'?: string;
    /**
     * Organization VAT ID. Only applies for b2b orders.
     * @type {string}
     * @memberof Customer
     */
    'vat_id'?: string;
}

