/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PickupLocationV1 } from './pickup-location-v1';
import { ProductV1 } from './product-v1';
import { TimeslotV1 } from './timeslot-v1';

/**
 * 
 * @export
 * @interface DeliveryDetailsV1
 */
export interface DeliveryDetailsV1 {
    /**
     * Carrier product name
     * @type {string}
     * @memberof DeliveryDetailsV1
     */
    'carrier'?: string;
    /**
     * 
     * @type {ProductV1}
     * @memberof DeliveryDetailsV1
     */
    'product'?: ProductV1;
    /**
     * 
     * @type {TimeslotV1}
     * @memberof DeliveryDetailsV1
     */
    'timeslot'?: TimeslotV1;
    /**
     * 
     * @type {PickupLocationV1}
     * @memberof DeliveryDetailsV1
     */
    'pickup_location'?: PickupLocationV1;
}

