/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Dimensions
 */
export interface Dimensions {
    /**
     * The product\'s height as used in the merchant\'s webshop. Non-negative. Measured in millimeters.
     * @type {number}
     * @memberof Dimensions
     */
    'height'?: number;
    /**
     * The product\'s width as used in the merchant\'s webshop. Non-negative. Measured in millimeters.
     * @type {number}
     * @memberof Dimensions
     */
    'width'?: number;
    /**
     * The product\'s length as used in the merchant\'s webshop. Non-negative. Measured in millimeters.
     * @type {number}
     * @memberof Dimensions
     */
    'length'?: number;
}

