/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DiscountLine
 */
export interface DiscountLine {
    /**
     * Descriptive name of discount
     * @type {string}
     * @memberof DiscountLine
     */
    'name': string;
    /**
     * Non-negative number. Quantity of the discount line item.
     * @type {number}
     * @memberof DiscountLine
     */
    'quantity': number;
    /**
     * Minor units. Includes tax, excludes discount. (Must be non-positive).  Example: -100 Euros should be -10000.
     * @type {number}
     * @memberof DiscountLine
     */
    'unit_price': number;
    /**
     * Non-negative value. The percentage value is represented with two implicit decimals. (max 10000)  Example: 25% should be 2500.
     * @type {number}
     * @memberof DiscountLine
     */
    'tax_rate': number;
    /**
     * Minor units. Includes tax and discount.   Example: -25 euros should be -2500 Value = (quantity x unit_price). (Must be non-positive)
     * @type {number}
     * @memberof DiscountLine
     */
    'total_amount': number;
    /**
     * Must be within ±1 of total_amount - total_amount \\* 10000 / (10000 + tax_rate). Should be non-positive
     * @type {number}
     * @memberof DiscountLine
     */
    'total_tax_amount': number;
    /**
     * The CRM reference to the gift-card that was entered by the user
     * @type {string}
     * @memberof DiscountLine
     */
    'reference'?: string;
    /**
     * The gift-card number that was entered by the user
     * @type {string}
     * @memberof DiscountLine
     */
    'merchant_data'?: string;
}

