/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MerchantUrls
 */
export interface MerchantUrls {
    /**
     * URL for the terms and conditions page of the merchant. The URL will be displayed inside the Klarna Checkout iFrame.(max 2000 characters) Example: \"https://merchant.com/terms\"
     * @type {string}
     * @memberof MerchantUrls
     */
    'terms': string;
    /**
     * URL for the checkout page of the merchant. (max 2000 characters) Example: \"https://merchant.com/checkout\"
     * @type {string}
     * @memberof MerchantUrls
     */
    'checkout': string;
    /**
     * URL of the merchant confirmation page. The consumer will be redirected back to the confirmation page if the authorization is successful after the customer clicks on the ‘Place Order’ button inside checkout. The special characters of the confirmation URL should be encoded, e.g. the \"space\" character should be written as \"%20\". Then, on top of that, the whole confirmation URL should be encoded. E.g. the \"space\" character should become \"%2520\". (max 2000 characters) Example: \"https://merchant.com/confirmation\"
     * @type {string}
     * @memberof MerchantUrls
     */
    'confirmation': string;
    /**
     * URL that will be used for push notification when an order is completed. Should be different than checkout and confirmation URLs. (max 2000 characters) Example: \"https://merchant.com/push\"
     * @type {string}
     * @memberof MerchantUrls
     */
    'push': string;
    /**
     * URL that will be requested for final merchant validation. (must be https, max 2000 characters) Example: \"https://merchant.com/validation\"
     * @type {string}
     * @memberof MerchantUrls
     */
    'validation'?: string;
    /**
     * URL for notifications on pending orders. (max 2000 characters) Example: \"https://merchant.com/notification/{checkout.order.id}\"
     * @type {string}
     * @memberof MerchantUrls
     */
    'notification'?: string;
    /**
     * URL for the cancellation terms page of the merchant. The URL will be displayed in the email that is sent to the customer after the order is captured.(max 2000 characters) Example: \"https://merchant.com/terms/cancelation\"
     * @type {string}
     * @memberof MerchantUrls
     */
    'cancellation_terms'?: string;
    /**
     * URL for shipping option update. (must be https, max 2000 characters) Example: \"https://merchant.com/shippingoptionupdate\"
     * @type {string}
     * @memberof MerchantUrls
     */
    'shipping_option_update'?: string;
    /**
     * URL for shipping, tax and purchase currency updates. Will be called on address changes. (must be https, max 2000 characters) Example: \"https://merchant.com/addressupdate\"
     * @type {string}
     * @memberof MerchantUrls
     */
    'address_update'?: string;
    /**
     * URL for shipping, tax and purchase currency updates. Will be called on billing or shipping country changes. (must be https, max 2000 characters) Example: \"https://merchant.com/countrychange\"
     * @type {string}
     * @memberof MerchantUrls
     */
    'country_change'?: string;
}

