/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Checkbox } from './checkbox';
import { CheckboxV2 } from './checkbox-v2';

/**
 * 
 * @export
 * @interface Options
 */
export interface Options {
    /**
     * If true, validate callback must get a positive response to not stop purchase. Default: false.
     * @type {boolean}
     * @memberof Options
     */
    'require_validate_callback_success'?: boolean;
    /**
     * Acquiring channel for the order. The possible values are: <ul><li><em>ECOMMERCE for \"E-commerce\"</em></li><li><em>IN_STORE for \"Purchase in boutique\"</em></li><li><em>Default : ECOMMERCE</em></li></ul>
     * @type {string}
     * @memberof Options
     */
    'acquiring_channel'?: string;
    /**
     * If true, VAT is not displayed in Checkout\'s Order Summary page.
     * @type {boolean}
     * @memberof Options
     */
    'vat_removed'?: boolean;
    /**
     * If true, the consumer can enter different billing and shipping addresses. Default: false, except for purchase_country DE where default is: true
     * @type {boolean}
     * @memberof Options
     */
    'allow_separate_shipping_address'?: boolean;
    /**
     * Color for the buttons within the iFrame. Value should be a CSS hex color, e.g. \"#FF9900\"
     * @type {string}
     * @memberof Options
     */
    'color_button'?: string;
    /**
     * Color for the text inside the buttons within the iFrame. Value should be a CSS hex color, e.g. \"#FF9900\"
     * @type {string}
     * @memberof Options
     */
    'color_button_text'?: string;
    /**
     * Color for the checkboxes within the iFrame. Value should be a CSS hex color, e.g. \"#FF9900\"
     * @type {string}
     * @memberof Options
     */
    'color_checkbox'?: string;
    /**
     * Color for the checkboxes checkmark within the iFrame. Value should be a CSS hex color, e.g. \"#FF9900\"
     * @type {string}
     * @memberof Options
     */
    'color_checkbox_checkmark'?: string;
    /**
     * Color for the headers within the iFrame. Value should be a CSS hex color, e.g. \"#FF9900\"
     * @type {string}
     * @memberof Options
     */
    'color_header'?: string;
    /**
     * Color for the hyperlinks within the iFrame. Value should be a CSS hex color, e.g. \"#FF9900\"
     * @type {string}
     * @memberof Options
     */
    'color_link'?: string;
    /**
     * If true, the consumer cannot skip date of birth. Default: false
     * @type {boolean}
     * @memberof Options
     */
    'date_of_birth_mandatory'?: boolean;
    /**
     * A message that will be presented on the confirmation page under the headline \"Delivery\" (max 255 characters).
     * @type {string}
     * @memberof Options
     */
    'shipping_details'?: string;
    /**
     * If specified to false, title becomes optional. Only available for orders for country GB.
     * @type {boolean}
     * @memberof Options
     */
    'title_mandatory'?: boolean;
    /**
     * 
     * @type {Checkbox}
     * @memberof Options
     */
    'additional_checkbox'?: Checkbox;
    /**
     * If true, the user cannot skip national identification number in SE, NO, FI and DK. Default: false. In order to read the national identification number in the validation callback, please contact Klarna’s merchant support.
     * @type {boolean}
     * @memberof Options
     */
    'national_identification_number_mandatory'?: boolean;
    /**
     * Additional merchant defined field. e.g. Extra terms and conditions to show.  Example: \"ADDITIONAL MERCHANT TERMS! \\[terms link\\](https://merchant.com/extra_terms)\"
     * @type {string}
     * @memberof Options
     */
    'additional_merchant_terms'?: string;
    /**
     * If false, the consumer can skip the phone. Only available for orders in DACH countries.
     * @type {boolean}
     * @memberof Options
     */
    'phone_mandatory'?: boolean;
    /**
     * Radius for the border of elements within the iFrame.
     * @type {string}
     * @memberof Options
     */
    'radius_border'?: string;
    /**
     * A list of allowed customer types. Supported types: <b>person</b> & <b>organization</b>. Example: [\"person\",\"organization\"]
     * @type {Array<string>}
     * @memberof Options
     */
    'allowed_customer_types'?: Array<string>;
    /**
     * If true, the Order Detail subtotals view is expanded when the Klarna Checkout iFrame is loaded. Default: false
     * @type {boolean}
     * @memberof Options
     */
    'show_subtotal_detail'?: boolean;
    /**
     * 
     * @type {Array<CheckboxV2>}
     * @memberof Options
     */
    'additional_checkboxes'?: Array<CheckboxV2>;
    /**
     * Enable verification of National Identification Numbers only in Sweden, Finland and Norway. This option also make the national identification number mandatory. (Not applicable for countries outside of Sweden, Finland and Norway)
     * @type {boolean}
     * @memberof Options
     */
    'verify_national_identification_number'?: boolean;
    /**
     * Allow merchant to trigger auto capturing.
     * @type {boolean}
     * @memberof Options
     */
    'auto_capture'?: boolean;
    /**
     * If true, a client side validation is needed to complete the purchase
     * @type {boolean}
     * @memberof Options
     */
    'require_client_validation'?: boolean;
    /**
     * Enables the inline discount module
     * @type {boolean}
     * @memberof Options
     */
    'enable_discount_module'?: boolean;
    /**
     * If true, a optional VAT registration number field will be shown in the address form. Only applies for b2b orders.
     * @type {boolean}
     * @memberof Options
     */
    'show_vat_registration_number_field'?: boolean;
}

