/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProductIdentifiers
 */
export interface ProductIdentifiers {
    /**
     * The product\'s brand name as generally recognized by consumers. If no brand is available for a product, do not supply any value.
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'brand'?: string;
    /**
     * Color to be shown to the end customer (max 64 characters).
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'color'?: string;
    /**
     * The product\'s category path as used in the merchant\'s webshop. Include the full and most detailed category and separate the segments with \' > \'. (max 750 characters)  Example: \"Electronics Store > Computers & Tablets > Desktops\"
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'category_path'?: string;
    /**
     * The product\'s Global Trade Item Number (GTIN). Common types of GTIN are EAN, ISBN or UPC. Exclude dashes and spaces, where possible
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'global_trade_item_number'?: string;
    /**
     * The product\'s Manufacturer Part Number (MPN), which - together with the brand - uniquely identifies a product. Only submit MPNs assigned by a manufacturer and use the most specific MPN possible
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'manufacturer_part_number'?: string;
    /**
     * Size to be shown to the end customer (max 64 characters).
     * @type {string}
     * @memberof ProductIdentifiers
     */
    'size'?: string;
}

