/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Dimensions } from './dimensions';

/**
 * 
 * @export
 * @interface ShippingAttributes
 */
export interface ShippingAttributes {
    /**
     * The product\'s extra features, example [\"dangerous_goods\", \"bulky\"]
     * @type {Array<string>}
     * @memberof ShippingAttributes
     */
    'tags'?: Array<string>;
    /**
     * The product\'s weight as used in the merchant\'s webshop. Non-negative. Measured in grams.
     * @type {number}
     * @memberof ShippingAttributes
     */
    'weight'?: number;
    /**
     * 
     * @type {Dimensions}
     * @memberof ShippingAttributes
     */
    'dimensions'?: Dimensions;
}

