/*
Klarna Checkout API V3

The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * The name of the subscription product.  Example: \"Premium Account\"
     * @type {string}
     * @memberof Subscription
     */
    'name'?: string;
    /**
     * The cadence unit for this.  Example: \"DAY\"
     * @type {string}
     * @memberof Subscription
     */
    'interval': SubscriptionIntervalEnum;
    /**
     * The number of intervals.  Example: 30
     * @type {number}
     * @memberof Subscription
     */
    'interval_count': number;
}

type SubscriptionIntervalEnum = 'DAY' | 'WEEK' | 'MONTH' | 'YEAR'


